Contribution change between two entities
sibyl-dev/sibylapp2 pull request #51
Opened 2023-07-25 15:26 UTC by wei-enwang

A new page is created to examine the contribution value change when feature values change. Currently, the page only allows users to select entities from the dataset. Therefore, the next step might be to add API to allow users to create customized data and see what the feature contributions for their data will be.

2023-07-26 20:00 UTC, zyteka requested changes
Great job with this! This will be a really helpful page, especially once we factor in the concept of time

2023-07-26 21:33 UTC, wei-enwang commented on sibylapp/view/entity_difference.py
> +    show_legend()
This is what I set for right now. What do you think?
![Screen Shot 2023-07-26 at 5 32 11 PM](https://github.com/sibyl-dev/sibylapp2/assets/22818610/7d33172a-4ca0-4dc6-81e2-10d86b834e0a)
Here's what I wrote in the sidebar.
![Screen Shot 2023-07-26 at 5 30 11 PM](https://github.com/sibyl-dev/sibylapp2/assets/22818610/6dbbd45c-2fe0-4de7-b910-cab6c958e61c)

2023-07-27 13:32 UTC, zyteka approved these changes
Looks great! Just two little things and then please go ahead and merge

2023-07-27 13:32 UTC, zyteka commented on .gitignore
> +.vscode/
Nitpick but can you move this down below the `#pycharm` comment, with a comment `vscode`?

2023-07-27 13:32 UTC, zyteka commented on pages/4_Compare_Cases.py
> +import streamlit as st
Thinking about this a bit more, can you move this page to before "Understand the model"? That way the first three pages have local explanations, and the last page has a global explanation

2023-07-27 13:58 UTC, merged